services:
  dispatcher:
    build: ./dispatcher
    container_name: dispatcher
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8001
      - USER_SERVICE_URL=http://user-service:8002
      - PRODUCT_SERVICE_URL=http://product-service:8003
      - MONGO_URI=mongodb://dispatcher-mongo:27017
      - DATABASE_NAME=dispatcher_db
    depends_on:
      - auth-service
      - user-service
      - product-service
      - dispatcher-mongo
    networks:
      - microservice-net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    expose:
      - "8001"
    env_file:
      - ./auth-service/.env
    depends_on:
      - auth-mongo
    networks:
      - microservice-net

  user-service:
    build: ./user-service
    container_name: user-service
    expose:
      - "8002"
    env_file:
      - ./user-service/.env
    depends_on:
      - user-mongo
    networks:
      - microservice-net

  product-service:
    build: ./product-service
    container_name: product-service
    expose:
      - "8003"
    env_file:
      - ./product-service/.env
    depends_on:
      - product-mongo
    networks:
      - microservice-net

  dispatcher-mongo:
    image: mongo:latest
    container_name: dispatcher-mongo
    expose:
      - "27017"
    volumes:
      - dispatcher_mongo_data:/data/db
    networks:
      - microservice-net

  auth-mongo:
    image: mongo:latest
    container_name: auth-mongo
    expose:
      - "27017"
    volumes:
      - auth_mongo_data:/data/db
    networks:
      - microservice-net

  user-mongo:
    image: mongo:latest
    container_name: user-mongo
    expose:
      - "27017"
    volumes:
      - user_mongo_data:/data/db
    networks:
      - microservice-net

  product-mongo:
    image: mongo:latest
    container_name: product-mongo
    expose:
      - "27017"
    volumes:
      - product_mongo_data:/data/db
    networks:
      - microservice-net

volumes:
  dispatcher_mongo_data:
  auth_mongo_data:
  user_mongo_data:
  product_mongo_data:

networks:
  microservice-net:
    driver: bridge