version: '3.9'

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8001"

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8002:8002"

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8003:8003"

  dispatcher:
    build: ./dispatcher
    container_name: dispatcher
    ports:
      - "8000:8000"